export const tablePageStyles = {
  page: { maxWidth: "900px", margin: "0 auto", padding: "2rem" },
  header: { marginBottom: "2rem" },
  eyebrow: {
    fontSize: "0.72rem",
    fontWeight: 700,
    letterSpacing: "3px",
    textTransform: "uppercase",
    color: "#D4621A",
    marginBottom: "0.25rem",
  },
  title: {
    fontFamily: "var(--font-display)",
    fontSize: "2rem",
    color: "#3B1F0A",
    fontWeight: 700,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
    gap: "1.25rem",
  },
  card: {
    background: "#fff",
    borderRadius: "16px",
    padding: "1.5rem",
    boxShadow: "0 4px 20px rgba(59,31,10,0.10)",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    animation: "fadeInUp 0.4s ease both",
    position: "relative",
    overflow: "hidden",
  },
  accent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "4px",
    background: "linear-gradient(90deg, #D4621A, #E8A923)",
  },
  icon: { fontSize: "2.5rem" },
  name: {
    fontFamily: "var(--font-display)",
    fontSize: "1.4rem",
    color: "#3B1F0A",
    fontWeight: 700,
  },
  capacity: {
    fontSize: "0.85rem",
    color: "#9B6A3A",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  metaRow: { display: "flex", gap: "0.75rem", flexWrap: "wrap" },
  statusBadge: (active) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    padding: "4px 12px",
    borderRadius: "20px",
    fontSize: "0.72rem",
    fontWeight: 700,
    background: active ? "#DCFCE7" : "#FEE2E2",
    color: active ? "#16A34A" : "#DC2626",
  }),
  idText: {
    fontSize: "0.68rem",
    color: "#C0A878",
    fontFamily: "monospace",
    marginTop: "auto",
  },
};
