export const navbarStyles = {
  nav: {
    background: `linear-gradient(135deg, #3B1F0A 0%, #5C2E10 100%)`,
    padding: "0 2rem",
    height: "68px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    zIndex: 100,
    boxShadow: "0 2px 20px rgba(59,31,10,0.4)",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    textDecoration: "none",
  },
  brandIcon: {
    fontSize: "26px",
  },
  brandText: {
    fontFamily: "var(--font-display)",
    color: "#E8A923",
    fontSize: "1.4rem",
    fontWeight: 700,
    letterSpacing: "-0.5px",
  },
  brandSub: {
    color: "#FDF6E3",
    fontSize: "0.65rem",
    fontWeight: 300,
    letterSpacing: "2px",
    textTransform: "uppercase",
    display: "block",
    marginTop: "2px",
    marginLeft: "5px",
  },
  links: {
    display: "flex",
    gap: "0.25rem",
    alignItems: "center",
  },
  link: (active) => ({
    background: active ? "rgba(232,169,35,0.15)" : "transparent",
    color: active ? "#E8A923" : "#FDF6E3",
    border: active ? "1px solid rgba(232,169,35,0.4)" : "1px solid transparent",
    padding: "6px 14px",
    borderRadius: "8px",
    fontSize: "0.85rem",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.2s",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  }),
  logoutBtn: {
    background: "rgba(212,98,26,0.2)",
    color: "#E8A923",
    border: "1px solid rgba(212,98,26,0.4)",
    padding: "6px 14px",
    borderRadius: "8px",
    fontSize: "0.85rem",
    fontWeight: 700,
    cursor: "pointer",
    marginLeft: "8px",
    transition: "all 0.2s",
  },
};

export const footerStyles = {
  footer: {
    background: "linear-gradient(135deg, #3B1F0A 0%, #2A1508 100%)",
    color: "#FDF6E3",
    padding: "3rem 2rem 1.5rem",
    marginTop: "auto",
  },
  grid: {
    maxWidth: "1100px",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr",
    gap: "2rem",
    paddingBottom: "2rem",
    borderBottom: "1px solid rgba(232,169,35,0.2)",
  },
  title: {
    fontFamily: "var(--font-display)",
    color: "#E8A923",
    fontSize: "1.3rem",
    marginBottom: "0.5rem",
  },
  desc: {
    fontSize: "0.85rem",
    color: "rgba(253,246,227,0.7)",
    lineHeight: 1.7,
  },
  colTitle: {
    fontWeight: 700,
    color: "#E8A923",
    marginBottom: "0.75rem",
    fontSize: "0.9rem",
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  colItem: {
    fontSize: "0.85rem",
    color: "rgba(253,246,227,0.7)",
    marginBottom: "0.4rem",
    cursor: "default",
  },
  bottom: {
    maxWidth: "1100px",
    margin: "1.25rem auto 0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: "0.78rem",
    color: "rgba(253,246,227,0.4)",
  },
  badge: {
    background: "rgba(232,169,35,0.15)",
    border: "1px solid rgba(232,169,35,0.3)",
    color: "#E8A923",
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "0.72rem",
    fontWeight: 700,
  },
};
