export const loginStyles = {
  wrapper: {
    minHeight: "100vh",
    background:
      "linear-gradient(145deg, #FDF6E3 0%, #F5E6C8 50%, #EDD5A3 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "2rem",
    position: "relative",
    overflow: "hidden",
  },
  bg: {
    position: "absolute",
    inset: 0,
    opacity: 0.04,
    backgroundImage: `repeating-linear-gradient(45deg, #3B1F0A 0, #3B1F0A 1px, transparent 0, transparent 50%)`,
    backgroundSize: "20px 20px",
    pointerEvents: "none",
  },
  card: {
    background: "#fff",
    borderRadius: "20px",
    boxShadow: "0 20px 60px rgba(59,31,10,0.2)",
    width: "100%",
    maxWidth: "420px",
    overflow: "hidden",
    animation: "fadeInUp 0.6s ease",
    position: "relative",
    zIndex: 1,
  },
  header: {
    background: "linear-gradient(135deg, #3B1F0A, #5C2E10)",
    padding: "2rem",
    textAlign: "center",
  },
  headerIcon: { fontSize: "2.5rem", marginBottom: "0.5rem" },
  headerTitle: {
    fontFamily: "var(--font-display)",
    color: "#E8A923",
    fontSize: "1.8rem",
    fontWeight: 700,
  },
  headerSub: {
    color: "rgba(253,246,227,0.7)",
    fontSize: "0.82rem",
    marginTop: "0.25rem",
  },
  body: { padding: "2rem" },
  label: {
    display: "block",
    fontSize: "0.82rem",
    fontWeight: 700,
    color: "#3B1F0A",
    marginBottom: "0.4rem",
    letterSpacing: "0.5px",
    textTransform: "uppercase",
  },
  inputWrap: {
    position: "relative",
    marginBottom: "1.25rem",
  },
  inputIcon: {
    position: "absolute",
    left: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: "1rem",
    pointerEvents: "none",
  },
  input: {
    width: "85%",
    padding: "10px 12px 10px 36px",
    border: "2px solid #E8D5B0",
    borderRadius: "10px",
    fontSize: "0.95rem",
    fontFamily: "var(--font-body)",
    color: "#3B1F0A",
    background: "#FFFDF7",
    transition: "border-color 0.2s",
    outline: "none",
  },
  btn: {
    width: "100%",
    padding: "12px",
    background: "linear-gradient(135deg, #D4621A, #E8A923)",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    fontSize: "1rem",
    fontWeight: 700,
    cursor: "pointer",
    marginTop: "0.5rem",
    letterSpacing: "0.5px",
    transition: "opacity 0.2s, transform 0.1s",
    fontFamily: "var(--font-body)",
  },
  error: {
    background: "#FEE2E2",
    border: "1px solid #FECACA",
    color: "#DC2626",
    padding: "10px 14px",
    borderRadius: "8px",
    fontSize: "0.85rem",
    marginBottom: "1rem",
    animation: "fadeIn 0.3s ease",
  },
  hint: {
    textAlign: "center",
    marginTop: "1.5rem",
    fontSize: "0.78rem",
    color: "rgba(59,31,10,0.5)",
  },
  hintBox: {
    background: "#FDF6E3",
    border: "1px dashed #E8A923",
    borderRadius: "8px",
    padding: "10px",
    marginTop: "1rem",
    fontSize: "0.78rem",
    color: "#5C2E10",
  },
};
