export const productStyles = {
  page: { maxWidth: "1100px", margin: "0 auto", padding: "2rem" },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "2rem",
    flexWrap: "wrap",
    gap: "1rem",
  },
  titleGroup: {},
  eyebrow: {
    fontSize: "0.72rem",
    fontWeight: 700,
    letterSpacing: "3px",
    textTransform: "uppercase",
    color: "#D4621A",
    marginBottom: "0.25rem",
  },
  title: {
    fontFamily: "var(--font-display)",
    fontSize: "2rem",
    color: "#3B1F0A",
    fontWeight: 700,
  },
  meta: { color: "#9B6A3A", fontSize: "0.85rem", marginTop: "0.25rem" },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: "1.5rem",
  },
  card: {
    background: "#fff",
    borderRadius: "16px",
    overflow: "hidden",
    boxShadow: "0 4px 20px rgba(59,31,10,0.10)",
    transition: "transform 0.25s, box-shadow 0.25s",
    cursor: "pointer",
    animation: "fadeInUp 0.5s ease both",
  },
  imgWrap: {
    height: "180px",
    overflow: "hidden",
    background: "#F5E6C8",
    position: "relative",
  },
  img: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transition: "transform 0.4s",
  },
  badge: {
    position: "absolute",
    top: "10px",
    left: "10px",
    background: "linear-gradient(135deg, #D4621A, #E8A923)",
    color: "#fff",
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "0.7rem",
    fontWeight: 700,
    textTransform: "capitalize",
  },
  cardBody: { padding: "1.25rem" },
  cardName: {
    fontFamily: "var(--font-display)",
    fontSize: "1.15rem",
    color: "#3B1F0A",
    fontWeight: 600,
    marginBottom: "0.4rem",
  },
  cardDesc: {
    fontSize: "0.82rem",
    color: "#9B6A3A",
    marginBottom: "1rem",
    lineHeight: 1.5,
  },
  cardFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTop: "1px solid #F5E6C8",
    paddingTop: "0.75rem",
  },
  price: {
    fontFamily: "var(--font-display)",
    fontSize: "1.2rem",
    fontWeight: 700,
    color: "#D4621A",
  },
  detailBtn: {
    background: "#FDF6E3",
    border: "1px solid #E8D5B0",
    borderRadius: "8px",
    padding: "5px 12px",
    fontSize: "0.78rem",
    fontWeight: 700,
    color: "#3B1F0A",
    cursor: "pointer",
    transition: "all 0.2s",
    TextDecoder: "none",
  },
};

export const productDetailStyles = {
  page: { maxWidth: "900px", margin: "0 auto", padding: "2rem" },
  backBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    background: "none",
    border: "1px solid #E8D5B0",
    borderRadius: "8px",
    padding: "7px 16px",
    fontSize: "0.85rem",
    color: "#3B1F0A",
    cursor: "pointer",
    marginBottom: "1.5rem",
    fontFamily: "var(--font-body)",
    fontWeight: 600,
    transition: "all 0.2s",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "2rem",
    animation: "fadeInUp 0.5s ease",
  },
  imgMain: {
    height: "320px",
    borderRadius: "16px",
    overflow: "hidden",
    background: "#F5E6C8",
  },
  img: { width: "100%", height: "100%", objectFit: "cover" },
  thumbs: {
    display: "flex",
    gap: "8px",
    marginTop: "10px",
    flexWrap: "wrap",
  },
  thumb: (active) => ({
    width: "60px",
    height: "60px",
    borderRadius: "10px",
    overflow: "hidden",
    border: active ? "2px solid #D4621A" : "2px solid transparent",
    cursor: "pointer",
    transition: "border-color 0.2s",
    flexShrink: 0,
  }),
  thumbImg: { width: "100%", height: "100%", objectFit: "cover" },
  info: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },
  category: {
    display: "inline-block",
    background: "linear-gradient(135deg, #D4621A, #E8A923)",
    color: "#fff",
    padding: "4px 14px",
    borderRadius: "20px",
    fontSize: "0.75rem",
    fontWeight: 700,
    textTransform: "capitalize",
    width: "fit-content",
  },
  name: {
    fontFamily: "var(--font-display)",
    fontSize: "2rem",
    color: "#3B1F0A",
    fontWeight: 700,
    lineHeight: 1.2,
  },
  desc: { fontSize: "0.95rem", color: "#9B6A3A", lineHeight: 1.7 },
  price: {
    fontFamily: "var(--font-display)",
    fontSize: "2.2rem",
    color: "#D4621A",
    fontWeight: 700,
  },
  metaRow: {
    display: "flex",
    gap: "1.5rem",
    flexWrap: "wrap",
  },
  metaItem: { fontSize: "0.8rem", color: "#9B6A3A" },
  metaLabel: {
    fontWeight: 700,
    color: "#5C2E10",
    display: "block",
    marginBottom: "2px",
  },
  statusBadge: (active) => ({
    display: "inline-block",
    padding: "4px 12px",
    borderRadius: "20px",
    fontSize: "0.75rem",
    fontWeight: 700,
    background: active ? "#DCFCE7" : "#FEE2E2",
    color: active ? "#16A34A" : "#DC2626",
  }),
};
